print("Day converter Program")
num_day =int(input("Input numbe of Day --> "))
print(num_day,"Days --> Hour",24*num_day,"Hours")
print(num_day,"Days --> Minutes",60*24*num_day,"Minutes")
print(num_day,"Days --> Seconds",60*60*24*num_day,"Secods")